### ISSUE TITLE
很期待，现在此项目已经开发完成了吗？

### ISSUE THREAD

**Issue by yuzhanglong** [lhr0909/feishu-blog#1]
飞书的知识库模式真的很好用，但是不能公开访问，看到本仓库觉得这个问题迎刃而解了！！❤️

**Comment by lhr0909** [comment]
已经基本可以用了。图片估计需要花点时间测试，不错正常用来写blog应该是问题不大了。不过飞书文档貌似是支持对外共享的，只是没有自定义域名。我写这个库和yuque-blog的初衷主要是想利用这些平台作为CMS，发布自己的网站使用，这样的话，更新内容就不需要再进入代码。
